[project]
version = "0.0.0"
name = "python-copier-template"
description = "A template for Python projects"
requires-python = ">=3.13,<4"
dependencies = ["click==8.1.7", "copier==9.4.1", "ruamel-yaml==0.18.6"]
